# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_event_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='web_url',
        ),
    ]
