# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_event_web_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_rsvp',
            field=models.BooleanField(default=False),
        ),
    ]
